### PR TITLE
CAP-332 Process opaque whiteouts as immediate as explicit whiteouts

### PR DESCRIPTION
**Pull request by andreas-kupries**
Ref https://jira.suse.com/browse/CAP-332

The original code defered the deletion until after unpacking completed. This had the effect of wrongly deleting the just-placed files and directories, instead of the files and directories of the previous layer.

Example from the ticket is the `stratos:canary` docker image which lost cert and ui definition files during unpacking, completely breaking it on all platforms where the groot-btrfs plugin is active (`minikube`, `CaaSP`).
    
 By deleting immediately the files and directories of the previous layer are removed, as required.

:warning: __Note__ that proper operation of this fix relies on whiteout marker files to come before any new files or directories in the tar stream.
    
:warning: Note further that the existing machinery in the driver was not removed as it is unclear how much of it is still referenced elsewhere. The fix as-is simply ensures that this machinery is not triggered.

----

Testing was done in a Vagrant/minikube setup.
- Build releases as normal.
- Compile packages as normal. This brings in all the regular packages needed.
- Replace the `container-host-files/etc/scf/config/.final_releases/groot-btrfs-*/packages/groot-btrfs.tgz` package tarball with one containing the patch (Only one file, `tar.go` has to be replaced).
- Locate the `groot-btrfs` package in the compilation cache:
  `ls -ld /home/vagrant/.fissile/compilation/*/*/compiled/bin/groot-btrfs`
- Remove the entire cache directory for the package (path above `compiled/...`).
- Recompile packages, it should recompile only `groot-btrfs`.
- Build images as normal.
- Deploy scf and uaa as normal.
- Log into CF, create an org and space to work in, create a CF securitygroup defined by `[{"destination": "0.0.0.0-255.255.255.255","protocol": "all" }]` and bind that SG to running (`cf bind-running-security-group ...`, use your chosen name of the SG).
- Deploy `stratos:canary` via `cf push stratos -o splatform/suse-stratos:canary -m 256M -k 512M`.
- Before the change stratos was broken.
- With this change `stratos.cf-dev.io` should be available, using standard user/password, showing itself as a running CF application.
- Note: If stratos does not even start the most likely cause is a forgotten setup of the CF security group.

### CODE REVIEW

**Review by jimmykarily — APPROVED** [review]
I'm not sure how we can end up with a layer that creates a file in a directory that it also whites out but maybe that's a normal operation (?). Also [the code here](https://github.com/SUSE/groot-btrfs/blob/master/base_image_puller/base_image_puller.go#L278) won't do anything anymore but it looks as if it was carefully placed there which makes me wonder if there is something else we break. Given I don't understand this completely and that QA passes I have to approve this PR. I remember we were just copying code from the old driver so maybe we messed up the order of things somehow.

**Comment by jimmykarily** [comment]
For reference in case someone else also reviews: https://github.com/opencontainers/image-spec/blob/master/layer.md#opaque-whiteout

**Comment by andreas-kupries** [comment]
> I'm not sure how we can end up with a layer that creates a file in a directory that it also whites out but maybe that's a normal operation (?).

I suspect it is normal operation for Docker(file). In the stratos image the relevant layers had a `FOO/.wp..wp..opq` marker file entry, which is the opaque whiteout directive (OWD) instructing us to clear the old files and directories under `FOO/`, followed by entries for `FOO/...`, the new files and directories to create, for different values of path `FOO`.

> Also [the code here](https://github.com/SUSE/groot-btrfs/blob/master/base_image_puller/base_image_puller.go#L278) won't do anything anymore but it looks as if it was carefully placed there which makes me wonder if there is something else we break.

Yes, this is the old machinery which handled the directives for opaque whiteout after the directory was populated with the new files. I left that in the code for caution, despite this code never triggering anymore as `unpackOutput.OpaqueWhiteouts` will now always be empty.

> Given I don't understand this completely and that QA passes I have to approve this PR. I remember we were just copying code from the old driver so maybe we messed up the order of things somehow.

Overlayfs and Btrfs are quite different in how they construct the stack of layers in the filesystem. Overlayfs can get away with handling the OWDs after populating a layer because it is a filesystem attribute on the directory. Btrfs does not have that. You make the subvolume snapshot on top of the previous layer and then you can, actually have to, edit that directly to remove things, and thus this has to happen before repopulating, you cannot delay and defer.

**Comment by gaktive** [comment]
Do we need someone else to review this prior to merger? This has left the associated Jira work item in limbo.

**Pull request merged**
